#!/bin/sh

set -e

heatsim="$1"

echo "Running check N=1: 1x1"
mpirun --oversubscribe -n 1 "$heatsim" --dim-x 1 --dim-y 1 --input ./images/earth-medium.png --iterations 1 --output ./images/check1.png

echo "Running check N=10: 2x5"
mpirun --oversubscribe -n 10 "$heatsim" --dim-x 2 --dim-y 5 --input ./images/earth-medium.png --iterations 1 --output ./images/check10.png

echo "Running check N=16: 4x4"
mpirun --oversubscribe -n 16 "$heatsim" --dim-x 4 --dim-y 4 --input ./images/earth-medium.png --iterations 1 --output ./images/check16.png

echo "Running check N=32: 8x4"
mpirun --oversubscribe -n 32 "$heatsim" --dim-x 8 --dim-y 4 --input ./images/earth-medium.png --iterations 1 --output ./images/check32.png

sha256sum --check ./images/check1.checksum ./images/check10.checksum ./images/check16.checksum ./images/check32.checksum
